const languageOptions = [
  { value: 'javascript', label: 'JavaScript' },
  { value: 'html', label: 'HTML-5' },
  { value: 'css', label: 'CSS-3' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'csharp', label: 'C#' },
  { value: 'php', label: 'PHP' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'swift', label: 'Swift' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'rust', label: 'Rust' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'scala', label: 'Scala' },
  { value: 'dart', label: 'Dart' },
  { value: 'lua', label: 'Lua' },
  { value: 'cplus', label: 'C++' },
  { value: 'c', label: 'C' },
  { value: 'r', label: 'R' },
  { value: 'perl', label: 'Perl' },
  { value: 'sql', label: 'SQL' },
  { value: 'objectivec', label: 'Objective-C' },
  { value: 'haskell', label: 'Haskell' },
  { value: 'elixir', label: 'Elixir' },
  { value: 'groovy', label: 'Groovy' },
  { value: 'shell', label: 'Shell' },
  { value: 'visualbasic', label: 'Visual Basic' },
  { value: 'assembly', label: 'Assembly' },
  { value: 'matlab', label: 'MATLAB' },
  { value: 'scratch', label: 'Scratch' },
  { value: 'cobol', label: 'COBOL' },
  { value: 'fortran', label: 'FORTRAN' },
  { value: 'lisp', label: 'Lisp' },
  { value: 'prolog', label: 'Prolog' },
  { value: 'smalltalk', label: 'Smalltalk' },
  { value: 'basic', label: 'BASIC' },
  { value: 'pascal', label: 'Pascal' },
  { value: 'plsql', label: 'PL/SQL' },
  { value: 'swiftui', label: 'SwiftUI' },
  { value: 'reactnative', label: 'React Native' },
  { value: 'angular', label: 'Angular' },
  { value: 'vuejs', label: 'Vue.js' },
  { value: 'spring', label: 'Spring' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'express', label: 'Express.js' },
  { value: 'django', label: 'Django' },
  { value: 'flask', label: 'Flask' },
  { value: 'rails', label: 'Ruby on Rails' },
  { value: 'dotnet', label: '.NET' },
  { value: 'react', label: 'React' },
  { value: 'ember', label: 'Ember.js' },
  { value: 'clojure', label: 'Clojure' },
  { value: 'erlang', label: 'Erlang' },
  { value: 'fsharp', label: 'F#' },
  { value: 'ocaml', label: 'OCaml' },
  { value: 'perl6', label: 'Perl 6' },
  { value: 'racket', label: 'Racket' },
  { value: 'scheme', label: 'Scheme' },
  { value: 'sml', label: 'Standard ML' },
  { value: 'bash', label: 'Bash' },
  { value: 'perl5', label: 'Perl 5' },
  { value: 'ksh', label: 'Korn shell' },
  { value: 'zsh', label: 'Zsh' },
  { value: 'awk', label: 'Awk' },
  { value: 'sed', label: 'Sed' },
  { value: 'ada', label: 'Ada' },
  { value: 'forth', label: 'Forth' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'csh', label: 'C shell' },
  { value: 'fish', label: 'Fish' },
  { value: 'tcsh', label: 'Tcsh' },
  { value: 'sh', label: 'sh' },
  { value: 'squirrel', label: 'Squirrel' },
  { value: 'go', label: 'Go' },
  { value: 'raku', label: 'Raku' },
  { value: 'julia', label: 'Julia' },
  { value: 'nim', label: 'Nim' },
  { value: 'crystal', label: 'Crystal' },
  { value: 'haxe', label: 'Haxe' },
  { value: 'reasonml', label: 'ReasonML' },
];

export default languageOptions;
