import { FaJsSquare } from 'react-icons/fa';
import { FaHtml5 } from 'react-icons/fa';
import { FaCss3Alt } from 'react-icons/fa';
import { FaPython } from 'react-icons/fa';
import { FaJava } from 'react-icons/fa';
import { FaPhp } from 'react-icons/fa';
import { FaSwift } from 'react-icons/fa';
import { FaRust } from 'react-icons/fa';
import { FaRProject } from 'react-icons/fa';
import {
  FaDatabase,
  FaApple,
  FaTerminal,
  FaMicrosoft,
  FaCalculator,
  FaCode,
  FaLambda,
  FaHeart,
  FaPuzzlePiece,
  FaMicrochip,
  FaMobileAlt,
  FaLeaf,
  FaServer,
  FaGem,
} from 'react-icons/fa';
import { FaVuejs } from 'react-icons/fa';
import { FaNodeJs } from 'react-icons/fa';
import { FaAngular } from 'react-icons/fa';
import { FaErlang } from 'react-icons/fa';
import { FaEmber } from 'react-icons/fa';
import { DiFsharp } from 'react-icons/di';
import {
  SiC,
  SiCplusplus,
  SiCsharp,
  SiDart,
  SiLua,
  SiReact,
  SiScala,
  SiTypescript,
  SiKotlin,
  SiFlask,
  SiRuby,
  SiApachegroovy,
  SiHaskell,
  SiClojure,
} from 'react-icons/si';
import { GiCamel } from 'react-icons/gi';

const languages = {
  javascript: <FaJsSquare color="#f7df1e" />,
  html: <FaHtml5 color="#e34f26" />,
  css: <FaCss3Alt color="#1572b6" />,
  python: <FaPython color="#3776ab" />,
  java: <FaJava color="#007396" />,
  csharp: <SiCsharp color="#239120" />,
  php: <FaPhp color="#8892bf" />,
  ruby: <SiRuby color="#cc342d" />,
  swift: <FaSwift color="#f05138" />,
  typescript: <SiTypescript color="#007acc" />,
  rust: <FaRust color="#000000" />,
  kotlin: <SiKotlin color="#7f52ff" />,
  scala: <SiScala color="#dc322f" />,
  dart: <SiDart color="#00b4ab" />,
  lua: <SiLua color="#2c2d72" />,
  'c++': <SiCplusplus color="#f34b7d" />,
  cplus: <SiCplusplus color="#f34b7d" />,
  c: <SiC color="#a8b9cc" />,
  r: <FaRProject color="#276dc3" />,
  perl: <GiCamel color="#0093B2" />,
  sql: <FaDatabase color="#F29111" />,
  objectivec: <FaApple color="#999999" />,
  haskell: <SiHaskell color="#5D4F85" />,
  elixir: <FaHeart color="#6E4A7E" />,
  groovy: <SiApachegroovy color="#4298B8" />,
  shell: <FaTerminal color="#89e051" />,
  visualbasic: <FaMicrosoft color="#0175C2" />,
  assembly: <FaMicrochip color="#007396" />,
  matlab: <FaCalculator color="#0076A8" />,
  scratch: <FaPuzzlePiece color="#4D97EA" />,
  cobol: <FaCode color="#220000" />,
  fortran: <FaCode color="#734F96" />,
  lisp: <FaCode color="#7F5AB6" />,
  prolog: <FaCode color="#6D5ACF" />,
  smalltalk: <FaCode color="#596706" />,
  basic: <FaCode color="#0000FF" />,
  pascal: <FaCode color="#E3F171" />,
  plsql: <FaDatabase color="#f0ad4e" />,
  swiftui: <FaSwift color="#ffac45" />,
  reactnative: <FaMobileAlt color="#61dafb" />,
  angular: <FaAngular color="#dd0031" />,
  vuejs: <FaVuejs color="#41b883" />,
  spring: <FaLeaf color="#6db33f" />,
  laravel: <FaPhp color="#f4645f" />,
  nodejs: <FaNodeJs color="#43853d" />,
  express: <FaServer color="#000000" />,
  django: <FaPython color="#4584b6" />,
  flask: <SiFlask color="#000000" />,
  rails: <FaGem color="#cc0000" />,
  dotnet: <FaMicrosoft color="#5c2d91" />,
  react: <SiReact color="#61dafb" />,
  ember: <FaEmber color="#f23819" />,
  clojure: <SiClojure color="#5881d8" />,
  erlang: <FaErlang color="#a90533" />,
  fsharp: <DiFsharp color="#1b82c7" />,
  ocaml: <FaCode color="#3be133" />,
  racket: <FaCode color="#960122" />,
  scheme: <FaCode color="#1e4aec" />,
  sml: <FaCode color="#dc3d31" />,
  bash: <FaTerminal color="#000000" />,
  ksh: <FaTerminal color="#000000" />,
  zsh: <FaTerminal color="#000000" />,
  awk: <FaCode color="#77cc00" />,
  sed: <FaCode color="#64b970" />,
  ada: <FaCode color="#02f88c" />,
  forth: <FaCode color="#341708" />,
  powershell: <FaTerminal color="#012456" />,
  csh: <FaTerminal color="#000000" />,
  fish: <FaTerminal color="#000000" />,
  tcsh: <FaTerminal color="#000000" />,
  sh: <FaTerminal color="#000000" />,
  squirrel: <FaCode color="#800000" />,
  go: <FaCode color="#00ADD8" />,
  raku: <FaCode color="#0000fb" />,
  julia: <FaCode color="#a270ba" />,
  nim: <FaCode color="#ffc107" />,
  crystal: <FaCode color="#000000" />,
  haxe: <FaCode color="#EA8220" />,
  reasonml: <FaCode color="#db4c39" />,
};

export default languages;
